### PR TITLE
onping event

### PR DESCRIPTION
**Pull request by Hiale**

### CODE REVIEW

**Comment by eidheim** [comment]
Sorry for the late reply, I'll try have a look at this Tomorrow or the day after.

**Comment by RichLewis007** [comment]
Adding ping/pong messages would be helpful in the examples, to show how to avoid timeouts. @eidheim are you going to approve this, or does more work need to be done? Thanks!

**Comment by eidheim** [comment]
I never could decide what to do with this PR, and the server has to be considered too (this PR is on the client only). However, @RichLewis007 , you can send ping yourself, you just have to add the correct `fin_rsv_opcode`. At the moment, the client and server handles ping responses (pong) automatically, but again you still have to send the ping yourself.

**Comment by RichLewis007** [comment]
OK, thanks for the info!

**Comment by eidheim** [comment]
on_ping and on_pong handlers has finally been added!

**Pull request closed without merging**
