### PR TITLE
Added pointer check before async_write

### PR DESCRIPTION
**Pull request by ar90n**
When I send some data to closed connection, the program make segmentation fault.
I want to avoid this crash.

### CODE REVIEW

**Comment by eidheim** [comment]
Great, Ill have a look at this Tomorrow. Might have to add a mutex just to be sure.

**Comment by eidheim** [comment]
Or even better: insert the connection sharer ptr into the lamda.

**Comment by eidheim** [comment]
I fixed this in https://github.com/eidheim/Simple-WebSocket-Server/commit/e28735336a055d37ac176f6dee297549f69c2028 by keeping the connection object alive till the send_from_queue function is finished. Would you mind testing this latest version, if it works in your case?

**Comment by eidheim** [comment]
I'm not very happy with the double connection in `connection->send_queue.emplace_back(connection, ...`, I'll try find a better solution for this later.

**Comment by ar90n** [comment]
Thank you very much!! 
The latest version works very well.

**Comment by eidheim** [comment]
Happy to help, and thank you for finding this issue and its cause:)

**Pull request merged**
