### PR TITLE
Send closing signals on server stop.

### PR DESCRIPTION
**Pull request by jonatanolofsson**
Upon stopping the server, send closing signals by default.

### CODE REVIEW

**Comment by jonatanolofsson** [comment]
Incidentally, I have been unable to fully verify that this is actually working.. The send_close gets called alright, but in my (python websockets) client, I receive a 1006 status. I am not sure if this is due to the server or the client..

**Comment by eidheim** [comment]
Thank you. I think you would have to close the connection after the send_close has finished. This can be done in the send_close handler. One would also have to wait for these handlers to complete before stopping the io_service if it an internal io_service is used. 

I'll have to think a little about this. I can complete the implementation, but I do not have time before early next week.

**Comment by jonatanolofsson** [comment]
Closing in favor of @eidheim 's (future?) implementation

**Comment by eidheim** [comment]
I'm thinking about this from time to time. Currently, based on your commit, I have the current changes that I contemplate pushing to master:
```diff
diff --git a/server_ws.hpp b/server_ws.hpp
index d5ba4ef..8ae6001 100644
--- a/server_ws.hpp
+++ b/server_ws.hpp
@@ -6,6 +6,7 @@
 
 #include <array>
 #include <atomic>
+#include <future>
 #include <iostream>
 #include <limits>
 #include <list>
@@ -428,21 +429,27 @@ namespace SimpleWeb {
       }
     }
 
-    void stop(const int status=1000, const std::string reason="") noexcept {
+    /// Synchronously close current connections and stop server
+    void stop(const int status = 1001, const std::string reason = "") noexcept {
       if(acceptor) {
         error_code ec;
         acceptor->close(ec);
 
+        std::list<std::promise<void>> promises;
         for(auto &pair : endpoint) {
           std::unique_lock<std::mutex> lock(pair.second.connections_mutex);
           for(auto &connection : pair.second.connections) {
-            if(status > 0) {
-              connection->send_close(status, reason);
-            }
-            connection->close();
+            promises.emplace_back();
+            auto &promise = promises.back();
+            connection->send_close(status, reason, [connection, &promise](const error_code &) {
+              connection->close();
+              promise.set_value();
+            });
           }
           pair.second.connections.clear();
         }
+        for(auto &promise : promises)
+          promise.get_future().get();
 
         if(internal_io_service)
           io_service->stop();
```

I am, however, not sure if we should have two stop methods, for instance one additional that is called `close_and_stop` or something similar. Feedback is welcome.

**Comment by jonatanolofsson** [comment]
Except a general dislike for missing curly braces, I can't see anything wrong with it =)

**Comment by eidheim** [comment]
Long overdue, but I'm going to push these changes to master soon. However, I'll probably change the method signature to:
```c++
void stop() noexcept
```
and always use status code 1001 and reason "going away". Do you see a problem with that in your use cases?

**Comment by eidheim** [comment]
After some additional thought, my diff will not work if stop is called inside a handler (when one event loop is used). This issue has to be resolved in a different manner. For instance, making a new public method SocketServer::stop_accept that stops accepting new connections, and then manually send close messages to connected clients.

**Comment by eidheim** [comment]
With the new `stop_accept` function added in the above commit, one can cleanly close the connections for instance like this:
```c++
#include "server_ws.hpp"

using namespace std;

using WsServer = SimpleWeb::SocketServer<SimpleWeb::WS>;

int main() {
  WsServer server;
  server.config.port = 8080;

  auto &echo = server.endpoint["^/echo/?$"];

  echo.on_message = [](shared_ptr<WsServer::Connection> connection, shared_ptr<WsServer::Message> message) {
    auto send_stream = make_shared<WsServer::SendStream>();
    *send_stream << message->string();
    connection->send(send_stream);
  };

  std::unordered_set<WsServer::Connection *> connections;
  echo.on_open = [&connections](shared_ptr<WsServer::Connection> connection) {
    connections.emplace(connection.get());
  };

  echo.on_close = [&connections](shared_ptr<WsServer::Connection> connection, int /*status*/, const string & /*reason*/) {
    connections.erase(connection.get());
  };

  echo.on_error = [&connections](shared_ptr<WsServer::Connection> connection, const SimpleWeb::error_code & /*ec*/) {
    connections.erase(connection.get());
  };

  thread stop_thread([&server, &connections] {
    this_thread::sleep_for(chrono::seconds(30));
    server.stop_accept();
    server.io_service->post([&connections] {
      for(auto connection : connections)
        connection->send_close(1001, "going away");
    });
    while(!connections.empty())
      this_thread::sleep_for(chrono::milliseconds(50));
    server.stop();
  });
  stop_thread.detach();

  server.start();
}
```

**Pull request closed without merging**
